# Generated by Django 5.1.6 on 2025-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredgrove',
            name='area_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sacredgrove',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
