# Generated by Django 5.1.6 on 2025-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_app', '0002_alter_sacredgrove_area_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredgrove',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sacredgrove',
            name='district',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
