# Generated by Django 5.1.6 on 2025-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_app', '0004_pendingsacredgrove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredgrove',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
